spring:
  profiles:
    include: plugins
  agent:
    trace:
      methods:
        - org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider#findCandidateComponents(java.lang.String)
