spring:
  profiles:
    include: plugins
  agent:
    trace:
      methods:
        - method: 'org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider#findCandidateComponents(java.lang.String)'
        - method: 'org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider#findCandidateComponents(java.lang.String)'
