spring:
  profiles:
    include: plugins-extension
  agent:
    trace:
      methods:
        - method: 'java.net.URLClassLoader#findResource(java.lang.String)'
          can-retransform: true
        - method: 'sun.misc.Launcher$AppClassLoader#loadClass(java.lang.String, boolean)'
          can-retransform: true
