spring:
  profiles:
    include: plugins-extension
  agent:
    #方法调用统计
    trace:
      #屏蔽类加载器增强
      method-invoke-advisors:
    turbo:
      enabled-by-default: false
      swagger:
        enabled: false
      open-feign:
        enabled: false
