#端口
server:
  port: 9999

#方法调用统计
spring:
  application:
    name: 'agent'
  profiles:
    active: plugins
  main:
    allow-bean-definition-overriding: true
  agent:
    allow-overriding-default-properties: true
    output:
      home: arthas-output
      output-path: '${spring.agent.output.home}/output'
    #类加载器增强(解决SPY类加载不到的问题)
    class-loaders:
      enhance-loaders:
        - java.lang.ClassLoader
    #火焰图数据采集
    flame-graph:
      high-precision: false
      names: main
      interval: 1
      #高精度模式下此配置无效
      skip-trace:
        - java.arthas
        - com.taobao.arthas
    #方法调用统计
    trace:
      methods:
        - method: java.net.URLClassLoader#findResource(java.lang.String)
          can-retransform: true
        - method: sun.misc.Launcher$AppClassLoader#loadClass(java.lang.String, boolean)
          can-retransform: true

logging:
  config: 'classpath:logback.xml'
  file:
    path: ./logs
  level:
    root: warn
    com.taobao.arthas.core.profiling: info
    com.taobao.arthas.core.advisor: info
