#端口
server:
  port: 9999

#方法调用统计
spring:
  application:
    name: 'spring-boot-profiling'
  profiling:
    outputPath: arthas-output
    #类加载器增强
    class-loaders:
      enhance-loaders: java.lang.ClassLoader
    #火焰图数据采集
    thread:
      names: main
      interval: 5
    #方法调用统计
    trace:
      methods:
        - org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory#doCreateBean(java.lang.String, org.springframework.beans.factory.support.RootBeanDefinition, java.lang.Object[])
        - org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider#findCandidateComponents(java.lang.String)

logging:
  config: 'classpath:logback.xml'
  file:
    path: ./logs
  level:
    root: warn
