#端口
server:
  port: 9999

#方法调用统计
spring:
  application:
    name: 'spring-boot-profiling'
  main:
    allow-bean-definition-overriding: false
  agent:
    output:
      home: arthas-output
      output-path: '${spring.agent.output.home}/output'
    #类加载器增强(解决SPY类加载不到的问题)
    class-loaders:
      enhance-loaders:
        - java.lang.ClassLoader
    #火焰图数据采集
    thread:
      names: main
      interval: 5
    #方法调用统计
    trace:
      methods:
        - method: java.net.URLClassLoader#findResource(java.lang.String)
          can-retransform: true
        - method: sun.misc.Launcher$AppClassLoader#loadClass(java.lang.String, boolean)
          can-retransform: true

logging:
  config: 'classpath:logback.xml'
  file:
    path: ./logs
  level:
    root: warn
    com.taobao.arthas.core.profiling: info
    com.taobao.arthas.core.advisor: info
